name: Rust

on: [push, pull_request]

jobs:
  build_ubuntu-1804:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2
      - name: Install alsa
        run: sudo apt update && sudo apt install libasound2-dev libgtk-3-dev
      - uses: Swatinem/rust-cache@v1
      - uses: actions-rs/cargo@v1
        with:
          command: build
          args: --release 
      - name: Chmod +x
        run: chmod +x target/release/neothesia
      - name: zip binary
        run: zip -rj app.zip target/release/neothesia
      - uses: actions/upload-artifact@v2
        with:
          name: ubuntu-artifact-1804
          path: app.zip

